context("test-plotSingleSite")

test_that("The function plotSingleSite works", {
    data(zikv_align)
    data(zikv_tree)
    tr <- addMSA(zikv_tree, alignment = zikv_align)
    p <- lineagePath(tr)
    expect_error(plotSingleSite(p, 2, showPath = TRUE), NA)
    expect_error(plotSingleSite(p, 3, showPath = FALSE), NA)
})

test_that("Warnings in plotSingleSite works", {
    data(zikv_align)
    data(zikv_tree)
    tr <- addMSA(zikv_tree, alignment = zikv_align)
    p <- lineagePath(tr)
    expect_error(plotSingleSite(p, 0))
    muts <- fixationSites(p)
    expect_error(extractSite(muts, 0))
    expect_error(plotSingleSite(muts, 0))
    sp <- extractSite(muts, 139)
    nSP <- length(sp)
    expect_error(extractTips(sp, nSP + 1))
    expect_error(plot(sp, nSP + 1))
})
