# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getSimilarityMatrix <- function(alignedSeqs) {
    .Call('_sitePath_getSimilarityMatrix', PACKAGE = 'sitePath', alignedSeqs)
}

runTreemer <- function(tipPaths, alignedSeqs, simMatrixInput, similarity, getTips) {
    .Call('_sitePath_runTreemer', PACKAGE = 'sitePath', tipPaths, alignedSeqs, simMatrixInput, similarity, getTips)
}

divergentNode <- function(paths) {
    .Call('_sitePath_divergentNode', PACKAGE = 'sitePath', paths)
}

getReference <- function(refSeq, gapChar) {
    .Call('_sitePath_getReference', PACKAGE = 'sitePath', refSeq, gapChar)
}

ancestralPaths <- function(paths, minLen) {
    .Call('_sitePath_ancestralPaths', PACKAGE = 'sitePath', paths, minLen)
}

summarizeAA <- function(seqs, siteIndex, tolerance) {
    .Call('_sitePath_summarizeAA', PACKAGE = 'sitePath', seqs, siteIndex, tolerance)
}

tableAA <- function(seqs, siteIndex) {
    .Call('_sitePath_tableAA', PACKAGE = 'sitePath', seqs, siteIndex)
}

minimizeEntropy <- function(nodeSummaries, minEffectiveSize) {
    .Call('_sitePath_minimizeEntropy', PACKAGE = 'sitePath', nodeSummaries, minEffectiveSize)
}

tip2colorEdge <- function(colorEdge, color, treeEdge, tips, rootNode) {
    .Call('_sitePath_tip2colorEdge', PACKAGE = 'sitePath', colorEdge, color, treeEdge, tips, rootNode)
}

