# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

trimTree <- function(tipPaths, alignedSeqs, similarity, getTips) {
    .Call('_sitePath_trimTree', PACKAGE = 'sitePath', tipPaths, alignedSeqs, similarity, getTips)
}

terminalNode <- function(paths) {
    .Call('_sitePath_terminalNode', PACKAGE = 'sitePath', paths)
}

pathBeforeDivergence <- function(paths) {
    .Call('_sitePath_pathBeforeDivergence', PACKAGE = 'sitePath', paths)
}

